#!/bin/bash


yum install -y \redhat-lsb-core \wget \rpmdevtools \rpm-build \createrepo \yum-utils


wget https://nginx.org/packages/centos/7/SRPMS/nginx-1.14.1-1.el7_4.ngx.src.rpm
rpm -ivh nginx-1.14.1-1.el7_4.ngx.src.rpm

wget ftp://ftp.fi.muni.cz/pub/openssl/source/openssl-1.1.1f.tar.gz
mv /home/vagrant/openssl-1.1.1f.tar.gz /root/
tar -xvf /root/openssl-1.1.1f.tar.gz


yum-builddep -y /root/rpmbuild/SPECS/nginx.spec
rpmbuild -bb /root/rpmbuild/SPECS/nginx.spec

yum localinstall -y /root/rpmbuild/RPMS/x86_64/nginx-1.14.1-1.el7_4.ngx.x86_64.rpm
systemctl start nginx

mkdir /usr/share/nginx/html/repo
cp /root/rpmbuild/RPMS/x86_64/nginx-1.14.1-1.el7_4.ngx.x86_64.rpm /usr/share/nginx/html/repo/
wget http://www.percona.com/downloads/percona-release/redhat/0.1-6/percona-release-0.1-6.noarch.rpm -O /usr/share/nginx/html/repo/percona-release-0.1-6.noarch.rpm

createrepo /usr/share/nginx/html/repo/
cp /vagrant/default.conf /etc/nginx/conf.d/default.conf


sudo nginx -t
sudo nginx -s reload

curl -a http://localhost/repo/

cp /vagrant/otus.repo /etc/yum.repos.d/otus.repo
yum repolist enabled | grep otus
sudo yum install percona-release -y
